import { useEffect, useState } from "react";
import { prefersReducedMotion } from "../utils.js";
import ascent from "../assets/maps/ascent.webp";
import haven from "../assets/maps/haven.webp";
import bind from "../assets/maps/bind.webp";
import icebox from "../assets/maps/icebox.webp";
import lotus from "../assets/maps/lotus.webp";
import split from "../assets/maps/split.webp";

// Valorant home-screen style animated backdrop: slowly zooming map splashes
// that crossfade on a timer.
//
// Splashes are self-hosted resized WebP (~150 KB each vs 2-5 MB CDN PNGs),
// generated by scripts/fetch-assets.mjs and fingerprinted by Vite so the
// Caddyfile's immutable cache rule applies. The CDN URL is kept per map as a
// runtime fallback only. Map UUIDs verified 2026-07 against
// https://valorant-api.com/v1/maps
const MAPS = [
  { name: "Ascent", uuid: "7eaecc1b-4337-bbf6-6ab9-04b8f06b3319", local: ascent },
  { name: "Haven", uuid: "2bee0dc9-4ffe-519b-1cbd-7fbe763a6047", local: haven },
  { name: "Bind", uuid: "2c9d57ec-4431-9c5e-2939-8f9ef6dd5cba", local: bind },
  { name: "Icebox", uuid: "e2ad5c54-4114-a870-9641-8ea21279579a", local: icebox },
  { name: "Lotus", uuid: "2fe4ed3a-450a-948b-6d6b-e89a78e680a9", local: lotus },
  { name: "Split", uuid: "d960549e-485c-e861-8d71-aa9d1aed12a2", local: split },
];

const splash = (uuid) =>
  `https://media.valorant-api.com/maps/${uuid}/splash.png`;

const CYCLE_MS = 12000;

/**
 * One backdrop layer. Verifies the local asset decodes before painting it and
 * swaps to the CDN URL if it doesn't (background-image has no onerror, so the
 * probe uses an Image()). Layers that have faded out also pause their kenburns
 * animation via CSS (.backdrop-layer:not(.on)) instead of compositing forever.
 */
function Layer({ on, local, cdn }) {
  const [src, setSrc] = useState(local);
  // A layer mounts fresh each time its map comes around, so applying .on in
  // the same frame as insertion would skip the opacity transition (an instant
  // cut instead of the 2.4s crossfade). Arm it one frame after mount; the
  // reduced-motion CSS zeroes the transition, so that path stays instant.
  const [armed, setArmed] = useState(false);

  useEffect(() => {
    const raf = requestAnimationFrame(() =>
      requestAnimationFrame(() => setArmed(true)),
    );
    return () => cancelAnimationFrame(raf);
  }, []);

  useEffect(() => {
    const img = new Image();
    img.onerror = () => setSrc(cdn);
    img.src = local;
    return () => {
      img.onerror = null;
    };
  }, [local, cdn]);

  return (
    <div
      className={`backdrop-layer${on && armed ? " on" : ""}`}
      style={{ backgroundImage: `url(${src})` }}
    />
  );
}

export default function Backdrop() {
  // Only the current and previous layers are ever mounted — the 2.4s
  // crossfade needs exactly two, and each extra full-viewport layer used to
  // accumulate will-change GPU memory for the rest of the session.
  const [pair, setPair] = useState({ prev: null, cur: 0 });

  useEffect(() => {
    // Under reduced motion: keep a single static splash, no cycling.
    if (prefersReducedMotion()) return undefined;
    const timer = setInterval(() => {
      // Background tabs skip the tick entirely — no state churn, no decode
      // work for pixels nobody sees (assets are cached, so this is hygiene,
      // not bandwidth).
      if (document.hidden) return;
      setPair((p) => ({ prev: p.cur, cur: (p.cur + 1) % MAPS.length }));
    }, CYCLE_MS);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    // Preload the next splash so the crossfade never pops in blank.
    if (prefersReducedMotion()) return;
    const img = new Image();
    img.src = MAPS[(pair.cur + 1) % MAPS.length].local;
  }, [pair.cur]);

  const mounted = [];
  if (pair.prev != null && pair.prev !== pair.cur) mounted.push(pair.prev);
  mounted.push(pair.cur);

  return (
    <div className="backdrop" aria-hidden="true">
      {mounted.map((i) => (
        <Layer
          key={MAPS[i].uuid}
          on={i === pair.cur}
          local={MAPS[i].local}
          cdn={splash(MAPS[i].uuid)}
        />
      ))}
      <div className="backdrop-shade" />
      <span className="backdrop-map">{`// ${MAPS[pair.cur].name}`}</span>
    </div>
  );
}
