import { useState } from "react";
import gekko36 from "../assets/agents/gekko-36.webp";
import gekko88 from "../assets/agents/gekko-88.webp";
import omen36 from "../assets/agents/omen-36.webp";
import omen88 from "../assets/agents/omen-88.webp";
import brimstone36 from "../assets/agents/brimstone-36.webp";
import brimstone88 from "../assets/agents/brimstone-88.webp";
import sage36 from "../assets/agents/sage-36.webp";
import sage88 from "../assets/agents/sage-88.webp";
import cypher36 from "../assets/agents/cypher-36.webp";
import cypher88 from "../assets/agents/cypher-88.webp";

// Sentiment insignia system — game-flavored markers for good vs bad.
// Icons are self-hosted WebP (36px for the 18px chip, 88px for the 44px
// AgentBadge — both 2x for hidpi), generated by scripts/fetch-assets.mjs so
// the core UI contract no longer rides on a fan CDN's uptime. The CDN URL is
// kept as a runtime fallback, then the colored dot. Agent UUIDs verified
// 2026-07 against https://valorant-api.com/v1/agents?isPlayableCharacter=true
const AGENT_UUIDS = {
  gekko: "e370fa57-4757-3604-3648-499e1f642d3f",
  omen: "8e253930-4c05-31dd-1b6c-968525494517",
  brimstone: "9f0d8ba9-4140-b941-57d3-a7ad57c6b417",
  sage: "569fdd95-4d10-43ab-ca70-79becc718b46",
  cypher: "117ed9e3-49f3-6512-3ccf-0cada7e3823b",
};

const LOCAL_ICONS = {
  gekko: { 36: gekko36, 88: gekko88 },
  omen: { 36: omen36, 88: omen88 },
  brimstone: { 36: brimstone36, 88: brimstone88 },
  sage: { 36: sage36, 88: sage88 },
  cypher: { 36: cypher36, 88: cypher88 },
};

// Shared contract:
//   strength / positive  -> Gekko,     green  #4ade80, soft glow
//   weakness / negative  -> Omen,      red    #ff4655, slow 2s pulse
//   tactical tip         -> Brimstone, amber  #facc15
//   mental / reset       -> Sage,      cyan   #7dd3fc
//   pattern / neutral    -> Cypher,    off-white
export const SENTIMENTS = {
  strength: { agent: "gekko", color: "#4ade80" },
  weakness: { agent: "omen", color: "#ff4655" },
  tip: { agent: "brimstone", color: "#facc15" },
  mental: { agent: "sage", color: "#7dd3fc" },
  neutral: { agent: "cypher", color: "#ece8e1" },
};

export function agentIcon(kind) {
  const s = SENTIMENTS[kind] || SENTIMENTS.neutral;
  return `https://media.valorant-api.com/agents/${AGENT_UUIDS[s.agent]}/displayicon.png`;
}

function localIcon(kind, size) {
  const s = SENTIMENTS[kind] || SENTIMENTS.neutral;
  return LOCAL_ICONS[s.agent][size];
}

/** Fallback chain shared by both components: local asset -> CDN -> dot. */
function useIconSource(kind, size) {
  const [stage, setStage] = useState(0);
  const src = stage === 0 ? localIcon(kind, size) : agentIcon(kind);
  const failed = stage >= 2;
  const onError = () => setStage((s) => s + 1);
  return { src, failed, onError };
}

/**
 * Angled chip: agent icon + uppercase label. Falls back to a colored dot
 * if neither the local icon nor the CDN loads.
 */
export function Insignia({ kind, label }) {
  const safeKind = kind in SENTIMENTS ? kind : "neutral";
  const { src, failed, onError } = useIconSource(safeKind, 36);
  return (
    <span className={`insignia insignia-${safeKind}`}>
      {failed ? (
        <span className="insignia-dot" aria-hidden="true" />
      ) : (
        <img
          className="insignia-icon"
          src={src}
          alt=""
          loading="lazy"
          onError={onError}
        />
      )}
      <span className="insignia-label">{label}</span>
    </span>
  );
}

/** Larger standalone agent portrait (comms avatars etc.) with dot fallback. */
export function AgentBadge({ kind, size = 44 }) {
  const safeKind = kind in SENTIMENTS ? kind : "neutral";
  const { src, failed, onError } = useIconSource(safeKind, 88);
  if (failed) {
    return (
      <span
        className="insignia-dot insignia-dot-big"
        aria-hidden="true"
        style={{ background: SENTIMENTS[safeKind].color }}
      />
    );
  }
  return (
    <img
      src={src}
      alt=""
      width={size}
      height={size}
      loading="lazy"
      style={{ objectFit: "contain", display: "block" }}
      onError={onError}
    />
  );
}
